import "./globals.css";
import 'bootstrap/dist/css/bootstrap.rtl.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import "react-toastify/dist/ReactToastify.css"
import BootstrapClient from "@/components/lib/BootstrapClient"
import ToastifyClient from "@/components/lib/ToastifyClient"
import { Suspense } from "react";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<Suspense>
					{children}
					<ToastifyClient
						position="top-right"
						autoClose={2500}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick={true}
						rtl={true}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="colored" />
					<BootstrapClient />
				</Suspense>
			</body>
		</html >
	);
}
