import "./globals.css";
import "bootstrap/dist/css/bootstrap.rtl.min.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import "react-toastify/dist/ReactToastify.css"
import BootstrapClient from "@/components/libraries/BootstrapClient"
import Header from "@/components/layouts/Header"
import ToastifyClient from "@/components/libraries/ToastifyClient"
import Footer from "@/components/layouts/Footer"
import Providers from "@/components/libraries/ProgressBarClient"
import { AuthProvider } from "@/context/AuthContext"
import ReduxProvider from "@/redux/Provider"


export const metadata = {
	title: "فروشگاه غذا",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<AuthProvider>
					<ReduxProvider>
						<Providers>
							<Header />
							{children}
							<Footer />
							<ToastifyClient
								position="top-right"
								autoClose={2500}
								hideProgressBar={false}
								newestOnTop={false}
								closeOnClick={true}
								rtl={true}
								pauseOnFocusLoss
								draggable
								pauseOnHover
								theme="colored" />
							<BootstrapClient />
						</Providers>
					</ReduxProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
