import "./globals.css";
import 'bootstrap/dist/css/bootstrap.rtl.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import "react-toastify/dist/ReactToastify.css"
import BootstrapClient from "@/components/lib/BootstrapClient"
import ToastifyClient from "@/components/lib/ToastifyClient"
import Providers from "@/components/lib/ProgressBarClient"
import Header from "@/components/layouts/Header";
import Sidebar from "@/components/layouts/Sidebar";
import { Suspense } from "react";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<Suspense>
					<AuthProvider>
						<Providers>
							<Header />
							<div className="container-fluid">
								<div className="row">
									<Sidebar />
									<main className="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-4">
										{children}
									</main>
								</div>
							</div>
							<ToastifyClient
								position="top-right"
								autoClose={2500}
								hideProgressBar={false}
								newestOnTop={false}
								closeOnClick={true}
								rtl={true}
								pauseOnFocusLoss
								draggable
								pauseOnHover
								theme="colored" />
							<BootstrapClient />
						</Providers>
					</AuthProvider>
				</Suspense>
			</body>
		</html >
	);
}
